### ISSUE TITLE
Error #2

### ISSUE THREAD

**Issue by rhodan412** [Beast-Masters-addons/BattlePetQualityCheck#2]
1x ...dOns\BattlePetQualityCheck\BattlePetQualityCheck-v0.3.lua:153: attempt to call global 'quality_color' (a nil value)
[string "@BattlePetQualityCheck\BattlePetQualityCheck-v0.3.lua"]:153: in function <...dOns\BattlePetQualityCheck\BattlePetQualityCheck.lua:133>

Locals:
self = <unnamed> {
 0 = <userdata>
}
event = "PET_BATTLE_OPENING_DONE"
(for index) = 1
(for limit) = 3
(for step) = 1
i = 1
rarity = 2
SpeciesId = 3007
upgrade_text = "Already owns |cffa334eeRare|r"
owned_rarity = 4
name = "Rosetipped Spiderling"
(*temporary) = <function> defined @BattlePetQualityCheck\libs\BM-utils\addon\utils.lua:16
(*temporary) = <table> {
 DEFAULT_FONT_COLOR = <table> {
 }
 colorize = <function> defined @BattlePetQualityCheck\libs\BM-utils\addon\utils.lua:60
 IsWoWClassic = <function> defined @BattlePetQualityCheck\libs\BM-utils\addon\utils.lua:94
 version_check = <function> defined @BattlePetQualityCheck\libs\BM-utils\addon\utils.lua:39
 SplitCharacterString = <function> defined @BattlePetQualityCheck\libs\BM-utils\addon\utils.lua:121
 GetCharacterString = <function> defined @BattlePetQualityCheck\libs\BM-utils\addon\utils.lua:116
 ColorToHex = <function> defined @BattlePetQualityCheck\libs\BM-utils\addon\utils.lua:148
 ColorToRGB = <function> defined @BattlePetQualityCheck\libs\BM-utils\addon\utils.lua:131
 GetCharacterInfo = <function> defined @BattlePetQualityCheck\libs\BM-utils\addon\utils.lua:105
 DifficultyToNum = <function> defined @BattlePetQualityCheck\libs\BM-utils\addon\utils.lua:154
 printf = <function> defined @BattlePetQualityCheck\libs\BM-utils\addon\utils.lua:16
 SetDefaultFontColor = <function> defined @BattlePetQualityCheck\libs\BM-utils\addon\utils.lua:77
 parse_version = <function> defined @BattlePetQualityCheck\libs\BM-utils\addon\utils.lua:24
 GenerateHexColor = <function> defined @BattlePetQualityCheck\libs\BM-utils\addon\utils.lua:142
 CastSpellById = <function> defined @BattlePetQualityCheck\libs\BM-utils\addon\utils.lua:214
 ItemNameFromLink = <function> defined @BattlePetQualityCheck\libs\BM-utils\addon\utils.lua:208
 ItemIdFromLink = <function> defined @BattlePetQualityCheck\libs\BM-utils\addon\utils.lua:200
 DifficultyColorText = <function> defined @BattlePetQualityCheck\libs\BM-utils\addon\utils.lua:186
 DifficultyColor = <function> defined @BattlePetQualityCheck\libs\BM-utils\addon\utils.lua:170
 sprintf = <function> defined @BattlePetQualityCheck\libs\BM-utils\addon\utils.lua:20
 error = <function> defined @BattlePetQualityCheck\libs\BM-utils\addon\utils.lua:100
 cprint = <function> defined @BattlePetQualityCheck\libs\BM-utils\addon\utils.lua:87
}
(*temporary) = "Wild pet %d: %s%s|r (%s)"
(*temporary) = 1
(*temporary) = nil
(*temporary) = 2
(*temporary) = "attempt to call global 'quality_color' (a nil value)"
GetHighestOwnedPetQuality = <function> defined @BattlePetQualityCheck\BattlePetQualityCheck.lua:8
utils = <table> {
 DEFAULT_FONT_COLOR = <table> {
 }
 colorize = <function> defined @BattlePetQualityCheck\libs\BM-utils\addon\utils.lua:60
 IsWoWClassic = <function> defined @BattlePetQualityCheck\libs\BM-utils\addon\utils.lua:94
 version_check = <function> defined @BattlePetQualityCheck\libs\BM-utils\addon\utils.lua:39
 SplitCharacterString = <function> defined @BattlePetQualityCheck\libs\BM-utils\addon\utils.lua:121
 GetCharacterString = <function> defined @BattlePetQualityCheck\libs\BM-utils\addon\utils.lua:116
 ColorToHex = <function> defined @BattlePetQualityCheck\libs\BM-utils\addon\utils.lua:148
 ColorToRGB = <function> defined @BattlePetQualityCheck\libs\BM-utils\addon\utils.lua:131
 GetCharacterInfo = <function> defined @BattlePetQualityCheck\libs\BM-utils\addon\utils.lua:105
 DifficultyToNum = <function> defined @BattlePetQualityCheck\libs\BM-utils\addon\utils.lua:154
 printf = <function> defined @BattleP

**Comment by datagutten** [comment]
It seems like I released the 0.3 version without testing it. I made a bugfix release v0.4 where this and some other things are fixed.
